import { createContext, useState, useEffect } from 'react';

export const LangContext = createContext();

const translations = {
  'pt-BR': {
    // Login
    login: 'Entrar',
    register: 'Registrar',
    email: 'E-mail',
    password: 'Senha',
    dontHaveAccount: 'Não tem uma conta?',
    alreadyHaveAccount: 'Já tem uma conta?',
    
    // Dashboard
    dashboard: 'Painel',
    welcome: 'Bem-vindo',
    letsCreateOffers: 'Vamos criar ofertas incríveis hoje?',
    offersGeneratedToday: 'Ofertas Geradas Hoje',
    youtubeExtraction: 'Extração YouTube',
    unlimited: 'ILIMITADO',
    urlsPerDay: 'URLs/dia',
    extractUnlimited: 'Extraia comentários sem limites! 🎉',
    youtubeExtractor: 'Extrator YouTube',
    aiChat: 'Chat IA',
    offersKanban: 'Kanban de Ofertas',
    
    // YouTube Tab
    youtubeUrl: 'URL do YouTube',
    extractComments: 'Extrair Comentários',
    copyAll: 'Copiar Todos',
    useWithAI: 'Usar com IA',
    comments: 'comentários',
    likes: 'curtidas',
    
    // AI Chat
    selectAI: 'Selecione a IA',
    commentOrText: 'Comentário ou Texto',
    enterText: 'Digite ou cole o comentário...',
    generate: 'Gerar Oferta',
    copy: 'Copiar',
    offerGenerated: 'Oferta Gerada',
    clearPanel: 'Limpar Painel',
    completeAnalysis: 'Análise Completa de',
    copyCompleteAnalysis: 'Copiar Análise Completa',
    chooseDeliveryFormats: 'Escolha os Formatos de Entrega',
    clickOptionsBelow: 'Clique nas opções abaixo para gerar',
    howBuildSalesPage: 'Como deseja construir a Página de Vendas?',
    wordpress: 'WordPress',
    wordpressDesc: 'Manual/Elementor',
    quiz: 'Quiz',
    quizDesc: 'Funil diagnóstico',
    iaBuilder: 'IA Builder',
    iaBuilderDesc: 'Lovable/Gama',
    howStructureEbook: 'Como deseja estruturar o Ebook?',
    canva: 'Canva',
    canvaDesc: 'Design visual simples',
    gama: 'Gama',
    gamaDesc: 'Estrutura completa',
    generateCreativesCopy: 'Gerar Criativos e Copy?',
    creativesDesc: '5 posts estáticos + 5 vídeos curtos',
    generateCreatives: 'Gerar Criativos',
    creativesCount: '5 Posts + 5 Vídeos',
    
    // Kanban
    pending: 'Pendente',
    inExecution: 'Em Execução',
    modeling: 'Modelando',
    completed: 'Concluído',
    offersSaved: 'Ofertas Salvas',
    monitoring: 'Monitoramento',
    modelingTab: 'Modelagem',
    addMonitoring: 'Adicionar Monitoramento',
    addModeling: 'Adicionar Modelagem',
    monitoringProgress: 'Progresso do Monitoramento',
    creativesLabel: 'Criativos',
    daysElapsed: 'Dias decorridos',
    fanpage: 'Fanpage',
    salesPage: 'Página de Vendas',
    checkout: 'Checkout',
    moveToModeling: 'Mover p/ Modelagem',
    duplicate: 'Duplicar',
    monitoringForm: 'Formulário de Monitoramento',
    modelingForm: 'Formulário de Modelagem',
    title: 'Título',
    description: 'Descrição',
    salesPageCopy: 'Copy da Página de Vendas',
    creativeCopy: 'Copy de Criativo',
    notes: 'Anotações',
    createMonitoring: 'Criar Monitoramento',
    createModeling: 'Criar Modelagem',
    updateModeling: 'Atualizar Modelagem',
    monitoringInfo: 'O sistema irá monitorar automaticamente esta oferta por 7 dias.',
    modelingInfo: 'Use este espaço para organizar e documentar as ofertas que você está modelando.',
    approved: 'Aprovado',
    rejected: 'Reprovado',
    inProgress: 'Em Andamento',
    review: 'Revisão',
    
    // Admin
    admin: 'Administrador',
    overview: 'Visão Geral',
    users: 'Usuários',
    apiKeys: 'Chaves API',
    webhooks: 'Webhooks',
    
    // Plans
    plan: 'Plano',
    silver: 'PRATA',
    gold: 'OURO',
    diamond: 'DIAMANTE',
    
    // Common
    loading: 'Carregando...',
    save: 'Salvar',
    cancel: 'Cancelar',
    delete: 'Excluir',
    edit: 'Editar',
    status: 'Status',
    active: 'Ativo',
    inactive: 'Inativo',
    logout: 'Sair',
    managePlatform: 'Gerencie sua plataforma ViralTicket',
  },
  'en-US': {
    login: 'Login',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    
    dashboard: 'Dashboard',
    welcome: 'Welcome',
    letsCreateOffers: "Let's create amazing offers today?",
    offersGeneratedToday: 'Offers Generated Today',
    youtubeExtraction: 'YouTube Extraction',
    unlimited: 'UNLIMITED',
    urlsPerDay: 'URLs/day',
    extractUnlimited: 'Extract comments without limits! 🎉',
    youtubeExtractor: 'YouTube Extractor',
    aiChat: 'AI Chat',
    offersKanban: 'Offers Kanban',
    
    youtubeUrl: 'YouTube URL',
    extractComments: 'Extract Comments',
    copyAll: 'Copy All',
    useWithAI: 'Use with AI',
    comments: 'comments',
    likes: 'likes',
    
    selectAI: 'Select AI',
    commentOrText: 'Comment or Text',
    enterText: 'Enter or paste comment...',
    generate: 'Generate Offer',
    copy: 'Copy',
    offerGenerated: 'Offer Generated',
    clearPanel: 'Clear Panel',
    completeAnalysis: 'Complete Analysis by',
    copyCompleteAnalysis: 'Copy Complete Analysis',
    chooseDeliveryFormats: 'Choose Delivery Formats',
    clickOptionsBelow: 'Click options below to generate',
    howBuildSalesPage: 'How do you want to build the Sales Page?',
    wordpress: 'WordPress',
    wordpressDesc: 'Manual/Elementor',
    quiz: 'Quiz',
    quizDesc: 'Diagnostic funnel',
    iaBuilder: 'AI Builder',
    iaBuilderDesc: 'Lovable/Gama',
    howStructureEbook: 'How do you want to structure the Ebook?',
    canva: 'Canva',
    canvaDesc: 'Simple visual design',
    gama: 'Gama',
    gamaDesc: 'Complete structure',
    generateCreativesCopy: 'Generate Creatives & Copy?',
    creativesDesc: '5 static posts + 5 short videos',
    generateCreatives: 'Generate Creatives',
    creativesCount: '5 Posts + 5 Videos',
    
    pending: 'Pending',
    inExecution: 'In Progress',
    modeling: 'Modeling',
    completed: 'Completed',
    offersSaved: 'Saved Offers',
    monitoring: 'Monitoring',
    modelingTab: 'Modeling',
    addMonitoring: 'Add Monitoring',
    addModeling: 'Add Modeling',
    monitoringProgress: 'Monitoring Progress',
    creativesLabel: 'Creatives',
    daysElapsed: 'Days elapsed',
    fanpage: 'Fanpage',
    salesPage: 'Sales Page',
    checkout: 'Checkout',
    moveToModeling: 'Move to Modeling',
    duplicate: 'Duplicate',
    monitoringForm: 'Monitoring Form',
    modelingForm: 'Modeling Form',
    title: 'Title',
    description: 'Description',
    salesPageCopy: 'Sales Page Copy',
    creativeCopy: 'Creative Copy',
    notes: 'Notes',
    createMonitoring: 'Create Monitoring',
    createModeling: 'Create Modeling',
    updateModeling: 'Update Modeling',
    monitoringInfo: 'The system will automatically monitor this offer for 7 days.',
    modelingInfo: 'Use this space to organize and document the offers you are modeling.',
    approved: 'Approved',
    rejected: 'Rejected',
    inProgress: 'In Progress',
    review: 'Review',
    
    admin: 'Admin',
    overview: 'Overview',
    users: 'Users',
    apiKeys: 'API Keys',
    webhooks: 'Webhooks',
    
    plan: 'Plan',
    silver: 'SILVER',
    gold: 'GOLD',
    diamond: 'DIAMOND',
    
    loading: 'Loading...',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    status: 'Status',
    active: 'Active',
    inactive: 'Inactive',
    logout: 'Logout',
    managePlatform: 'Manage your ViralTicket platform',
  },
  'es-ES': {
    login: 'Iniciar sesión',
    register: 'Registrarse',
    email: 'Correo electrónico',
    password: 'Contraseña',
    dontHaveAccount: '¿No tienes una cuenta?',
    alreadyHaveAccount: '¿Ya tienes una cuenta?',
    
    dashboard: 'Panel',
    welcome: 'Bienvenido',
    letsCreateOffers: '¿Creamos ofertas increíbles hoy?',
    offersGeneratedToday: 'Ofertas Generadas Hoy',
    youtubeExtraction: 'Extracción YouTube',
    unlimited: 'ILIMITADO',
    urlsPerDay: 'URLs/día',
    extractUnlimited: '¡Extrae comentarios sin límites! 🎉',
    youtubeExtractor: 'Extractor YouTube',
    aiChat: 'Chat IA',
    offersKanban: 'Kanban de Ofertas',
    
    youtubeUrl: 'URL de YouTube',
    extractComments: 'Extraer Comentarios',
    copyAll: 'Copiar Todos',
    useWithAI: 'Usar con IA',
    comments: 'comentarios',
    likes: 'me gusta',
    
    selectAI: 'Seleccionar IA',
    commentOrText: 'Comentario o Texto',
    enterText: 'Ingrese o pegue el comentario...',
    generate: 'Generar Oferta',
    copy: 'Copiar',
    offerGenerated: 'Oferta Generada',
    clearPanel: 'Limpiar Panel',
    completeAnalysis: 'Análisis Completo de',
    copyCompleteAnalysis: 'Copiar Análisis Completo',
    chooseDeliveryFormats: 'Elige los Formatos de Entrega',
    clickOptionsBelow: 'Haz clic en las opciones para generar',
    howBuildSalesPage: '¿Cómo deseas construir la Página de Ventas?',
    wordpress: 'WordPress',
    wordpressDesc: 'Manual/Elementor',
    quiz: 'Quiz',
    quizDesc: 'Embudo diagnóstico',
    iaBuilder: 'AI Builder',
    iaBuilderDesc: 'Lovable/Gama',
    howStructureEbook: '¿Cómo deseas estructurar el Ebook?',
    canva: 'Canva',
    canvaDesc: 'Diseño visual simple',
    gama: 'Gama',
    gamaDesc: 'Estructura completa',
    generateCreativesCopy: '¿Generar Creativos y Copy?',
    creativesDesc: '5 posts estáticos + 5 videos cortos',
    generateCreatives: 'Generar Creativos',
    creativesCount: '5 Posts + 5 Videos',
    
    pending: 'Pendiente',
    inExecution: 'En Ejecución',
    modeling: 'Modelando',
    completed: 'Completado',
    offersSaved: 'Ofertas Guardadas',
    monitoring: 'Monitoreo',
    modelingTab: 'Modelado',
    addMonitoring: 'Agregar Monitoreo',
    addModeling: 'Agregar Modelado',
    monitoringProgress: 'Progreso del Monitoreo',
    creativesLabel: 'Creativos',
    daysElapsed: 'Días transcurridos',
    fanpage: 'Fanpage',
    salesPage: 'Página de Ventas',
    checkout: 'Checkout',
    moveToModeling: 'Mover a Modelado',
    duplicate: 'Duplicar',
    monitoringForm: 'Formulario de Monitoreo',
    modelingForm: 'Formulario de Modelado',
    title: 'Título',
    description: 'Descripción',
    salesPageCopy: 'Copy de Página de Ventas',
    creativeCopy: 'Copy de Creativo',
    notes: 'Notas',
    createMonitoring: 'Crear Monitoreo',
    createModeling: 'Crear Modelado',
    updateModeling: 'Actualizar Modelado',
    monitoringInfo: 'El sistema monitoreará automáticamente esta oferta durante 7 días.',
    modelingInfo: 'Usa este espacio para organizar y documentar las ofertas que estás modelando.',
    approved: 'Aprobado',
    rejected: 'Rechazado',
    inProgress: 'En Progreso',
    review: 'Revisión',
    
    admin: 'Administrador',
    overview: 'Resumen',
    users: 'Usuarios',
    apiKeys: 'Claves API',
    webhooks: 'Webhooks',
    
    plan: 'Plan',
    silver: 'PLATA',
    gold: 'ORO',
    diamond: 'DIAMANTE',
    
    loading: 'Cargando...',
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    edit: 'Editar',
    status: 'Estado',
    active: 'Activo',
    inactive: 'Inactivo',
    logout: 'Salir',
    managePlatform: 'Gestiona tu plataforma ViralTicket',
  },
};

export const LangProvider = ({ children }) => {
  const [language, setLanguage] = useState('pt-BR');

  useEffect(() => {
    const savedLang = localStorage.getItem('viralticket_language');
    if (savedLang) {
      setLanguage(savedLang);
    }
  }, []);

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('viralticket_language', lang);
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  // Função para retornar o idioma atual para a IA
  const getLanguageForAI = () => {
    return language;
  };

  return (
    <LangContext.Provider value={{ language, changeLanguage, t, getLanguageForAI }}>
      {children}
    </LangContext.Provider>
  );
};
